Gausslab-SeoulOffice/problems

- yunjae/card2.py
https://www.acmicpc.net/problem/2164
Used a queue via Python deque
> Baekjoon 2164

- dawn/mergeTwoSortedLists.java
You are given the heads of two sorted linked lists list1 and list2.
Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.
Return the head of the merged linked list.
##
Input: list1 = [1,2,4], list2 = [1,3,4]
Output: [1,1,2,3,4,4]
Input: list1 = [], list2 = []
Output: []
Input: list1 = [], list2 = [0]
Output: [0]
> 1121 mergeTwoSortedLists(java)

- yunjae/fibo_memoization.py
https://www.acmicpc.net/problem/10826
Solved recursively with memoization
> Baekjoon 10826

- HyoRim/16212.py
- 형준이는 수열을 하나 가지고 있다. 형준이는 수열을 정열적으로 정렬해보려 한다. 과연, 정렬할 수 있을까?
- https://www.acmicpc.net/problem/16212
> 백준 16212, 정열적인 정렬

- yunjae/diameterBT.py
- yunjae/fatigue.py
https://leetcode.com/problems/diameter-of-binary-tree/
Solved by using DFS
> LeetCode - Diameter of Binary Tree

- rotate_parentheses.py
- yunjae/func_dev.py
https://school.programmers.co.kr/learn/courses/30/lessons/42586
> Programmers Lv.2 - 기능개발

- yunjae/truck_crossing_bridge.py
https://school.programmers.co.kr/learn/courses/30/lessons/42583
> Programmers 스택/큐: 다리를 지나는 트럭

- yunjae/swimming_pool_1.py
- yunjae/swimming_pool_2.py
SWEA 1952번 문제 '수영장'입니다. 재귀와 DP 두 가지로 풀었습니다.
문제 링크: https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5PpFQaAQMDFAUq&
> SWEA 1952 (수영장)

- yunjae/ox_cumsum1.py
- yunjae/ox_cumsum2.py
백준 8958번 OX퀴즈(https://www.acmicpc.net/problem/8958)를 풀었습니다.
첫째 풀이는 스택을 이용했고, 풀어보니 낭비가 있는 것 같아 좀더 Pythonic하게도 풀어봤습니다.
> 백준 8959번 OX퀴즈

- yunjae/text_justification.py
파이썬을 이용한 풀이입니다.
다 풀고 보니 https://focalpoint.tistory.com/261 처럼 대부분 비슷한 발상으로 푸는 것 같네요... 
메모리 낭비가 좀 있겠지만 Greedy한 단어 묶음을 먼저 만들어놓고 진행하는 방식으로,
최대한 혼자 힘으로 접근하려고 노력했습니다.
파이썬은 문자열에 공백을 첨가하는 방법이 다양한데 이번 기회에 배워가네요! ([참고](https://velog.io/@tngus0325/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EB%AC%B8%EC%9E%90%EC%97%B4-%ED%8F%AC%EB%A7%B7%ED%8C%85-format-%ED%95%A8%EC%88%98%EC%99%80-f-%EB%AC%B8%EC%9E%90%EC%97%B4-%ED%8F%AC%EB%A7%B7%ED%8C%85%EC%9D%98-%ED%99%9C%EC%9A%A9-%EB%B0%A9%EB%B2%95))
> LeetCode 68 - Text Justification

- yunjae/perm_backtrack.py
- yunjae/perm_itertools.py
재귀 연습을 위해 풀어본 문제입니다. itertools에 포함된 permutations를 이용하는 경우도 많습니다.
> 백준 15654: N과 M (5)

- yunjae/jewel_n_stone1.py
- yunjae/jewel_n_stone2.py
해시테이블로 많이들 푸는 문제를 ~~파이썬의 묘미를 느낄 수 있는~~ 두 가지 방법으로 풀어봤습니다!
> LeetCode 771 - Jewels and Stones

- yunjae/rain_trap1.py
- yunjae/rain_trap2.py
https://leetcode.com/problems/trapping-rain-water/description/
투포인터와 스택을 사용한 풀이입니다.
투포인터 쪽이 더 직관적이고 '유형 암기'처럼 활용하기 쉬워 보이네요...
스택 풀이는 이 문제 처음 풀 때도 그랬지만 지금도 당장 쓰라고 하면 떠올리기 쉽지 않을 것 같아요
> 42. LeetCode - Trapping Rain Water

- yunjae/claw_machine.py
> 프로그래머스 - 크레인 인형뽑기 게임

- yunjae/pathfinding_game.py
https://school.programmers.co.kr/learn/courses/30/lessons/42892
좌표평면상에 이진트리를 그리는 부분이 어렵습니다.
규칙성을 빨리 찾아서 이진트리를 만들 수 있다면 나머지는 일반적인 이진트리 순회 문제와 비슷합니다.
> 프로그래머스 - 길찾기 게임

- yunjae/sheep_and_wolf.py
프로그래머스 - 양과 늑대 (2022 카카오 블라인드 채용)
https://school.programmers.co.kr/learn/courses/30/lessons/92343
이 문제는 출제 포인트가 어느 정도 정해져 있는 것 같습니다.
- DFS 문제임을 파악 
-  root가 무조건 양이라는 조건을 바탕으로 재귀를 사용하면 간편함을 파악
- sheep과 wolf 값을 바탕으로 재귀를 멈춰야 함을 파악
> 프로그래머스 - 양과 늑대 (카카오 기출)

- yunjae/exam_hall_divide.py
> 프로그래머스 - 시험장 나누기

- yunjae/immigration_desk.py
이진탐색 연습용으로 많이 쓰이는 문제입니다.
list comprehension과 변수 개수 최소화 등을 추가로 적용해서 소소하게 시간복잡도를 개선했습니다.
> 프로그래머스 - 입국심사

- yunjae/spicier.py
> 프로그래머스 - 더 맵게

- yunjae/dual_priority_q.py
힙 연습용 문제입니다. 
원래는 '라면공장'이라는 문제가 있었는데 링크가 사라져서 이걸로 대신 풀었어요... 🍜
> 프로그래머스 - 이중 우선순위 큐

- yunjae/park_stroll.py
델타탐색인데 여기에 iterable을 다루는 메소드 `all()`을 사용해서 조건을 검증했습니다
> 프로그래머스 - 공원 산책

- yunjae/bit_diff_by_two.py
비트 연산 연습용입니다. 
홀수 분기의 규칙성만 잘 파악한다면 쉬운 문제였습니다.
(이 문제 다음에는 비트마스킹을 풀어볼게요)
> 프로그래머스 - 2개 이하로 다른 비트

- yunjae/banned_user.py
정규표현식 + DFS + 비트마스킹 연습으로 선택한 문제입니다
> 프로그래머스 - 불량 사용자

- yunjae/sweats.py
그리디 알고리즘 연습문제입니다.
여벌 옷마저 잃어버린 경우까지 생각해야 하기 때문에 Lv1치고는 좀더 생각 정리가 필요합니다.
> 프로그래머스 - 체육복

- yunjae/big_number.py
상대적으로 쉬운 편이었습니다.
(다만 k개를 다 pop하지 않은 경우까지 신경써야 합니다)
> 프로그래머스 - 큰 수 만들기

- yunjae/process.py
큐 연습용 문제입니다. deque, enumerate(), any()를 같이 썼습니다.
> 프로그래머스 - 프로세스

- yunjae/prime_number1.py
- yunjae/prime_number2.py
완전탐색 연습용 문제입니다! 
DFS, permutations의 두 가지 방식으로 각각 풀어봤어요
> 프로그래머스 - 소수 찾기

- yunjae/express_with_n.py
DP 연습 문제입니다. set을 이용해서 푸는데, 점화식을 잘 찾아야 해서 어려웠네요 🥹
> 프로그래머스 - N으로 표현

- yunjae/integer_triangle.py
DP 문제 하나를 더 풀었습니다!
좋은 결과 있으시길 🙏
> 프로그래머스 - 정수 삼각형

- yunjae/phone_book.py
> 프로그래머스 - 전화번호 목록

- yunjae/farthest_nodes.py
BFS를 사용해서 풀었습니다.
단순 visited 여부만 확인하는 게 아니라 가장 먼 노드의 개수까지 세야 하는 문제입니다.
visited 여부 체크 방법이 문제의 성격에 따라 정말 천차만별이고 다양한 것 같아 따로 정리해둬야겠어요...
> 프로그래머스 - 가장 먼 노드

- yunjae/min_spanning_tree.py
> 백준 1197 - 최소 스패닝 트리

- yunjae/min_spanning_tree2.py
> 백준 1197 - 최소 스패닝 트리 (Prim)

- yunjae/gold_silver_transport.py
binary search 연습용 문제입니다.
초기 시작 조건을 잘 파악해야 풀리는 문제 같아요
> 프로그래머스 - 금과 은 운반

- yunjae/carpet1.py
- yunjae/carpet2.py
https://school.programmers.co.kr/learn/courses/30/lessons/42842
프로그래머스에서 제공하는 완전탐색 문제입니다!
이분탐색과 완전탐색 두 가지 방법으로 풀었습니다.
(원본이 사라진 줄 알았는데 아직 남아있네요)
> 프로그래머스 - 카펫

- yunjae/table_edit2.py
이미 풀었던 문제인데 연결리스트 클래스를 구현해서 다시 풀었습니다!
> 프로그래머스 - 표 편집 (연결리스트 클래스 구현)

- yunjae/addtwonums.py
- yunjae/best_time_to_buy_n_sell.py
- yunjae/string_compression.py
첫째는 완전탐색 문자열 문제로 풀어봤어요! 규칙성 찾는 게 쉽지 않네요...
둘째는 Brute Force로 풀 수 있는 문제이지만 조금 다르게 풀었습니다.
> 프로그래머스 - 문자열 압축 & LeetCode - Best Time to Buy and Sell Stock

- yunjae/halve_electric_network1.py
DFS 풀이입니다. 우선 스택 풀이부터 올리고 내일은 재귀를 올려볼게요!
> 프로그래머스 - 전력망을 둘로 나누기

- yunjae/robot_collision.py
완전 탐색 문제입니다~
파일을 올리고 pull request 만들려고 보니 create file한 내역이 반영이 안 되네요 🫤 
일단 파일 update를 추가로 해서 pull request 생성했습니다!
> 프로그래머스 - 로봇 충돌

- yunjae/proc_assignment.py
> 프로그래머스 - 과제 진행하기

- yunjae/complaint_outcome.py
defaultdict 연습용 문제입니다!
(바깥이 학교 축제라 오늘은 구경할 겸 간단하게 풀게요 🎆)
> 프로그래머스 - 신고 결과 받기

- yunjae/hotel_booking.py
저도 큐를 사용하는 문제를 풀어봤습니다! (잘 보니 며칠 전에 풀었던 문제와 비슷하네요)
이번주도 잘 부탁드려요 👍
> 프로그래머스 - 호텔 대실

- yunjae/ricochet_robot.py
중간에 풀다가 막혀서 시간이 좀 걸렸지만 로봇과 BFS에 관한 문제를 풀었습니다. 그것이 약속이니까 🙂‍↕️
> 프로그래머스 - 리코쳇 로봇 (BFS)

- yunjae/sort_cards.py
> 백준 1715 - 카드 정렬하기

- yunjae/defense_game.py
이분탐색으로도 풀 수 있는 문젠데 먼저 우선순위큐로 풀어봤어요!
> 프로그래머스 - 디펜스게임 (우선순위큐)

- yunjae/theft.py
DP를 사용하는 문젠데 제약조건이 재미있어서 풀어봤어요!
> 프로그래머스 - 도둑질 (DP)

- yunjae/travel_path.py
갑자기 편도선염에 걸려서 하루를 앓았네요 ㅠ 늦었지만 풀어서 올립니다!
> 프로그래머스 - 여행 계획 (DFS + 백트래킹)

- yunjae/archery.py
- yunjae/number_of_islands.py
비트마스킹을 그냥 뭔가 저장하는 용도로만 쓴 게 아니라 시각적으로 대응시켜서 낸 문제라 신기해서 골랐어요!
> 프로그래머스 - 양궁 대회

- yunjae/number_of_islands.py
재귀 DFS 연습문제입니다!
(create 한 직후에 바로 pull request 생성이 안 되는 문제가 가끔 있네요... 보시기 편하게 이미지로 코드 첨부합니다)
https://leetcode.com/problems/number-of-islands/
> LeetCode - Number of Islands (섬의 개수) (재귀 DFS)

- yunjae/constellation2.py
어제 풀었던 문제를 Prim으로 다시 풀었습니다! 비교해 보니 차이점이 생각보다 많네요
> 백준 4386 - 별자리 만들기 (re-solved with Prim)

- yunjae/min_array_sum.py
- yunjae/n-queen.py
백트래킹 문제풀이 분량을 좀더 채우기 위해 골랐습니다~
> 250623 SWEA 4881 - 배열최소합 + 250624 백준 9663 N-Queen (재귀, 백트래킹, DFS)

- yunjae/baby_shark.py
우선순위큐를 안 쓰고 그냥 풀었더니 시간초과가 떠서 조금 오래 걸렸습니다 🦈
> 250701 백준 16236 - 아기 상어 (BFS, 델타탐색, 우선순위큐)

- yunjae/zero_sum_four_digits.py
이 풀이는 PyPy3으로만 통과됩니다. 조만간 투포인터와 Python 3으로 다시 풀어볼게요!
> 250702 백준 7453 - 합이 0인 네 정수 (해시)

- yunjae/morecatmerrier.py
2배로 키워서 가장 빠르게 n에 도달하는 그리디 알고리즘 문제입니다!
> 250716 백준 27961 - 고양이는 많을수록 좋다 (그리디)

- yunjae/exercise2.py
기존 코드에서 if문을 줄이고 더 간결하게 refactoring했습니다.
> 250731 백준 1956 - 운동
